// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"mini-douyin/service/user/rpc/internal/logic"
	"mini-douyin/service/user/rpc/internal/svc"
	"mini-douyin/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.DouyinUserLoginRequest) (*user.DouyinUserLoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.DouyinUserRegisterRequest) (*user.DouyinUserRegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.DouyinUserRequest) (*user.DouyinUserResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
