// Code generated by goctl. DO NOT EDIT.
package types

type Douyin_user_login_request struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Douyin_user_login_response struct {
	User_id int    `json:"user_id"`
	Token   string `json:"token"`
}

type Douyin_user_register_request struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Douyin_user_register_response struct {
	User_id int    `json:"user_id"`
	Token   string `json:"token"`
}

type Douyin_user_request struct {
	User_id string `json:"user_id"`
	Token   string `json:"token"`
}

type Douyin_user_response struct {
	Status_code int              `json:"status_code"`
	Status_msg  string           `json:"status_msg"`
	User        Douyin_user_info `json:"user"`
}

type Douyin_user_info struct {
	Id             int    `json:"id"`
	Name           string `json:"name"`
	Follow_count   int    `json:"follow_count"`
	Follower_count int    `json:"follower_count"`
	Is_follow      bool   `json:"is_follow"`
}
